version: "3"

services:
  db:
    image: mongo:4.1
    container_name: db.ambassador
    environment:
      MONGO_INITDB_ROOT_USERNAME: ambassador
      MONGO_INITDB_ROOT_PASSWORD: ambassador
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/db:/data/db
    networks:
      - private

networks:
  private:
    driver: bridge
